"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { CheckCircle2 } from "lucide-react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { useCart } from "../context/CartContext";
import { useAuth } from "../context/AuthContext";
import { useEffect, Suspense } from "react";

function OrderSuccessContent() {
  const { clearCart } = useCart();
  const { isAuthenticated } = useAuth();

  const router = useRouter();
  const searchParams = useSearchParams();
  // In production, this would be passed from the checkout or generated by backend
  const orderNumber = searchParams.get("orderNumber") || "CO12345678";
  const isPendingVerification = searchParams.get("paymentStatus") === "pending_verification";

  
  useEffect(() => {
    // Clear cart after successful order
    clearCart();
  }, [clearCart]);

  const handleTrackOrder = () => {
    if (isAuthenticated) {
      router.push("/account/orders");
      return;
    }

    router.push("/signup?next=/account/orders&source=guest-order");
  };

  return (
    <>
      <main className="min-h-screen pt-24 pb-16 bg-gray-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-lg shadow-sm p-8 md:p-12 text-center">
            <div className="flex justify-center mb-6">
              <CheckCircle2 className="w-20 h-20 text-green-500" />
            </div>

            <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Thanks, your treats are in the oven! 🍰
            </h1>

            <p className="text-lg text-gray-600 mb-8">
              {isPendingVerification
                ? "Order received. We'll confirm your Mobile Money payment shortly."
                : "Your order has been received and we're baking up something delicious just for you!"}
            </p>

            <div className="bg-orange-50 rounded-lg p-6 mb-8">
              <p className="text-sm text-gray-600 mb-2">Order Number</p>
              <p className="text-2xl font-bold text-orange-500">{orderNumber}</p>
            </div>

            <div className="text-left bg-gray-50 rounded-lg p-6 mb-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">
                What&apos;s Next?
              </h2>
              <ul className="space-y-3 text-gray-700">
                <li className="flex items-start gap-2">
                  <span className="text-[#2A2C22] font-bold">1.</span>
                  <span>
                    {isPendingVerification
                      ? "We'll review your Mobile Money transaction and confirm payment shortly"
                      : "You'll receive a confirmation email shortly with your order details"}
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2A2C22] font-bold">2.</span>
                  <span>
                    {isPendingVerification
                      ? "Once confirmed, we'll start preparing your fresh-baked goodies"
                      : "We'll start preparing your fresh-baked goodies right away"}
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-[#2A2C22] font-bold">3.</span>
                  <span>
                    Your order will be ready for delivery/pickup at your scheduled time
                  </span>
                </li>
              </ul>
            </div>

            <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg mb-8">
              <p className="text-sm text-blue-800">
                📧 A confirmation email has been sent to your email address with tracking
                information.
              </p>
            </div>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button
                onClick={() => router.push("/")}
                className="bg-orange-500 hover:bg-orange-600 text-white font-semibold py-3 px-8 rounded-lg transition-colors"
              >
                Continue Shopping
              </button>
              <button
                onClick={handleTrackOrder}
                className="border border-gray-300 hover:bg-gray-50 text-gray-700 font-semibold py-3 px-8 rounded-lg transition-colors"
              >
                Track Order
              </button>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}

export default function OrderSuccessPage() {
  return (
    <>
      <Navbar />
      <Suspense fallback={
        <main className="min-h-screen pt-24 pb-16 bg-gray-50 flex items-center justify-center">
          <div className="text-gray-600">Loading...</div>
        </main>
      }>
        <OrderSuccessContent />
      </Suspense>
    </>
  );
}
